### ISSUE TITLE
Maybe 1.20.1 please?

### ISSUE THREAD

**Issue by DaytonaBlep** [pufferffish/wanparty#1]
I'd really like to see a version for 1.20.1 So, I can't afford to update all my mods just to test this mod on my server.

**Comment by pufferffish** [comment]
I'm cleaning up the codebase so I can target both forge and fabric with support for all minecraft versions >= 1.16.5, so hopefully I can get 1.20.1 supported this week

**Comment by pufferffish** [comment]
Added support for 1.20.1 for both Fabric and Forge
