### ISSUE TITLE
Not sure how mods are supported

### ISSUE THREAD

**Issue by ManicQuinn** [pufferffish/wanparty#2]
Do server side mods work or only client side?

**Comment by pufferffish** [comment]
You don't need server side mod to use wanparty to join singleplayer worlds. The server side mod is only for people who are hosting a server but cannot setup port forwarding for whatever reason, and in that case they can use wanparty on the server to create an address, and use that address to join the server with wanparty on client side.

-------- Original Message --------

**Comment by ManicQuinn** [comment]
What I mean is, do server side mods work the same way they work on servers? For example, server side mods usually only needs to be installed on the server, but in the case of Lan Worlds(Which is how I assume this mod works), say I have a server side mod on my client, and they don't have that mod, will the mod work as intended?

**Comment by pufferffish** [comment]
Generally speaking no,

Sent from Proton Mail mobile

-------- Original Message --------
