### ISSUE TITLE
1.20.4 support

### ISSUE THREAD

**Issue by JarlPenguin** [pufferffish/wanparty#3]
I've done it for Fabric here (hopefully it's not too bad?): https://github.com/JarlPenguin/wanparty/commit/10ef473dab5f69b249fcaa97116ae6afa89b76fc
Not sure about Forge, have zero experience with it.

Edit: seems to crash for some reason. https://paste.gg/p/anonymous/fa5f2ba0ad6f4e8fa973b54852a45027

**Comment by pufferffish** [comment]
The build system should theoratically handle forge as well, but just fabric support is good enough. Do you mind opening a PR?

**Comment by JarlPenguin** [comment]
Done
